### ISSUE TITLE
Syntax colouring for Perl is extremely limited 

### ISSUE THREAD

**Issue by ct2057** [alexpersian/Spacegray-Brackets#1]
There is a discrepancy between syntax colouring for Perl between Brackets and Sublime Text. You can see the differences in the images attached.

Sublime Text:
![sublime](https://cloud.githubusercontent.com/assets/10505988/8116973/e535acc4-107c-11e5-8055-ec6614faed9e.png)

Brackets:
![brackets](https://cloud.githubusercontent.com/assets/10505988/8116879/a15bc650-107c-11e5-8e04-bd4afb982423.png)

**Comment by alexpersian** [comment]
Thank you for bringing this to my attention. Perl wasn't one of my initial considerations, but I will look into the theme and see if I can get it working.

**Comment by alexpersian** [comment]
Sorry for the long hiatus on updates. I took some time to try and get the syntax highlighting for Perl to be more in line with Sublime Text, but was unable to yet. The underlying Codemirror tags that Brackets relies on cause some issues when trying to fix the colors for Perl.

I'm leaving this issue open though, and I will spend more time trying to fix the colors later.

**Comment by ct2057** [comment]
OK, thanks for the update (and the persistence!) on this issue 😊

**Comment by alexpersian** [comment]
Out of curiosity I compared a more well known theme, Monokai, and it seems like it has the same issues with Perl. I'll keep poking around with it, but it's pointing to not possible right now.

![Monokai](http://i.imgur.com/3CfP5sx.png)

**Comment by alexpersian** [comment]
Closing because of inability to successfully replicate Perl syntax highlighting.
